### ISSUE TITLE
Private fields support

### ISSUE THREAD

**Issue by olus2000** [sroehrl/theGame#12]
Some browsers, including Firefox, lack support for private fields in JS. Because of this the game crashes instantly after hitting "execute", and writes this error in the log:
```
JavaScript error: SyntaxError: private fields are not currently supported on line 11 for https://neoan.us/game/Game.js
```

**Comment by sroehrl** [comment]
Hey olus2000,
this is necessary to prevent direct access to game-relevant properties. (In other words: hacking the game is fun, but it shouldn't be as easy as overwriting properties.)

Chrome, Edge and even Opera and Safari shouldn't be a problem.

**BUT:** Firefox does support this, but it needs to be enabled:

[developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)

> This feature is behind thejavascript.options.experimental.private_fields preferences (needs to be set to true) and the javascript.options.experimental.private_methods preferences (needs to be set to true). To change preferences in Firefox, visit about:config.

**Comment by olus2000** [comment]
Unfortunately for now it's only available in nightly builds. It may be the push that makes me switch to firefox nightly because the game looks fun. Anyway I guess it's not your app that should change but firefox itself, so this is not a valid issue.
